---
- name: Deploy to tomcat
  hosts: web
  become: yes
  tasks: 
      - name: copy war to tomcat
        copy:
           src: "/var/lib/jenkins/workspace/MavenWebAnsibleLast/target/MavenWebAnsibleLast.war"
           dest: "/opt/tomcat/webapps/MavenWebAnsibleLast.war"
           remote_src: no
           
      - name: restart tomcat
        shell : |
           /opt/tomcat/bin/shutdown.sh || true 
           sleep 2
           /opt/tomcat/bin/startup.sh
